framework:
    messenger:

        transports:

            ping:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'

            aircraft:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    exchange:
                        name: airports
                    queues:
                        messages_airports: ~


        routing:
            'App\Messages\Ping': ping
