framework:
    messenger:

        transports:

            ping:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'

            airports:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    exchange:
                        name: airports
                    queues:
                        messages_airports: ~

            aircraft:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    exchange:
                        name: aircraft
                    queues:
                        messages_aircraft: ~


        routing:
            'App\Messages\Ping': ping
            'App\Messages\AirportData': airports
            'App\Messages\AircraftData': aircraft
