framework:
    messenger:

        transports:

            ping:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'

            heartbeat:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    exchange:
                        name: pulse
                    queues:
                        pulse_transponder_updates: ~
                        pulse_airport_updates: ~
                        pulse_aircraft_updates: ~

            airports:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    exchange:
                        name: airports
                    queues:
                        messages_airports: ~

            aircraft:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    exchange:
                        name: aircraft
                    queues:
                        messages_aircraft: ~

            transponders:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    exchange:
                        name: transponders
                    queues:
                        messages_transponders: ~
            traffic_events:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    exchange:
                        name: airtraffic
                    queues:
                        messages_events: ~


        routing:
            'App\Messages\Ping': ping
            'App\Messages\AirportData': airports
            'App\Messages\AircraftData': aircraft
            'App\Messages\IncomingTransponderStatus': transponders
            'App\Messages\TrafficUpdate': traffic_events
            'App\Messages\Heartbeat': heartbeat
